import Head from "next/head";
import { Container, CssBaseline, Box, Typography } from "@mui/material";
import { PartnerInsights } from "@/src/components/PartnerInsights/PartnerInsights";
import { questions } from "@/src/utils/quiz";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Box
        sx={{
          backgroundColor: "#F4D8CD",
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Container maxWidth="md">
          <Typography variant="h3" gutterBottom>
            Gifty
          </Typography>
          <PartnerInsights questions={questions} />
        </Container>
      </Box>
    </>
  );
}
